### ISSUE TITLE
Directory mode bug: deleting soft link is dangerous!

### ISSUE THREAD

**Issue by rsm-lisper** [lem-project/lem#1072]
In directory mode, when I delete soft link leading to directory, it does not delete soft link. Soft link stays as it was. But instead lem goes to target directory and **deletes its content**! :open_mouth:

**Before:**
![softlink0](https://github.com/lem-project/lem/assets/26094109/06d2546f-fc3e-4500-bcd8-76fd687cb5ab)

**During:**
![softlink1](https://github.com/lem-project/lem/assets/26094109/560fef93-2351-4bd6-91cc-719e6d333608)

**After:** :unamused:
![softlink2](https://github.com/lem-project/lem/assets/26094109/7c6ef9ab-3789-4f4d-b3cb-152ee877dd67)

**Comment by Sasanidas** [comment]
Oh my! This is indeed a big bug, thanks for the report! :alarm_clock:

**Comment by Sasanidas** [comment]
So, I added a fix that I think it does address the issue, the problem was that the command that was trigger for alll the deletions on directory-mode was ` (run-command `("rm" "-fr" ,file))`, with the r option enable, completely ignores the symlinks and kills the original host content, like you described a really undesired behavior! :face_exhaling:
