### ISSUE TITLE
Documentation for lem

### ISSUE THREAD

**Issue by jonBoone** [lem-project/lem#1226]
In order to facilitate my understanding, and ease onboarding of others in the future, I'd like to document the architecture of lem and the various components in this repository.

I'm looking for the following information:

1. What tools and format should I leverage?  GH-flavored markdown and lem itself?
2. What are the best resources for getting the insight into why decisions were made?  Is there a mailing list archive or something like that?  Should I just read the commit messages?
3. Where should I start?

**Comment by vindarel** [comment]
Hi, thanks for bringing a workforce to this task.

> 3. where should I start

IMO you cant start right away by writing content to Lem's website. There is a first overview of displaying concepts: https://lem-project.github.io/development/displaying/ and a short tutorial on how to write a major or minor mode: https://lem-project.github.io/usage/extension_modes/ When we wrote this we were like you, discovering Lem on the go while working on a feature and exploring its codebase.

> 2. What are the best resources for getting the insight into why decisions were made? Is there a mailing list archive or something like that? Should I just read the commit messages?

Lem is an Emacs-like editor, so that's a first hint… but Lem doesn't copy Emacs either, that is very clear by Lem's creator : )

There is no mailing list but the Discord. IMO a good place to ask for high-level explanations is Github discussions and Discord.

> 1. What tools and format should I leverage? GH-flavored markdown and lem itself?

What do you want to do, is writing on the website enough? There could be the goal of generating a documentation for Lem's internals, but I think hand-written tutorials are our first need. Though we could leverage a tool that allows to reference built-in functions and display its documentation. Such a tool could be [codex](https://github.com/CommonDoc/codex), [sphinx-contrib](https://sphinxcontrib-cldomain.russellsim.org/) and maybe more… (see awesome-cl).
