### ISSUE TITLE
Box symbol when using history in sdl2 on Mac

### ISSUE THREAD

**Issue by solanav** [lem-project/lem#1262]
When going back history and then going forward to the empty line, a box symbol appears.

![image](https://github.com/lem-project/lem/assets/32469597/71261bc6-d16f-4cc6-a772-ed4252f89541)

**Comment by cianoc** [comment]
I also get a 'box' in the project explorer:
![image](https://github.com/lem-project/lem/assets/355604/5088f47c-e30e-4666-bef2-874091556d97)

In both cases this is because the icon is missing. What is the best way to get all the icons needed by LEM?

I'd be happy to document this in the installation section for Mac computers.
