### ISSUE TITLE
How to use a custom Common Lisp implementation for Lisp code?

### ISSUE THREAD

**Issue by namandixit** [lem-project/lem#1312]
I am using Lem SDL v2.1.0 on Windows 10 x64.

Currently, any code written in a `.lisp` file executes in the Editor's own Lisp runtime. For example, in a Lisp source file:

```lisp
(lisp-implementation-type) => "SBCL"
sb-ext:*core-pathname* => #P"D:/Downloads/lem-windows-v2.1.0/lem-internal.exe"
(lisp-implementation-version) => "2.3.2"
```

However, I want to be able to use another Lisp implementation to run the code inside the Lisp file. How do I do this?  In Emacs, I would have set `inferior-lisp-program` in `init.el`, but I can't find any related Lem documentation.

(Note that I am **NOT** asking about changing the Lisp implementation that the Lem editor runs on, only my Lisp code. I tried looking into the documentation but couldn't find anything.)

**Comment by garlic0x1** [comment]
If you have Roswell installed, you can do `ros use ccl-bin` to switch to Clozure.  Lem will prioritize Roswell for starting slime if it is available.  Otherwise there are ways to set custom implementations exposed in `lem/extensions/lisp-mode/implementation.lisp`.

On my machine, slime will use Clozure after I run that `ros use` command.

**Comment by vindarel** [comment]
looks like we can use `C-u M-x slime RET <choose impl> RET` (which asks interactively for a roswell command)

https://lem-project.github.io/usage/common_lisp/#start-a-repl-with-another-lisp-core
