### ISSUE TITLE
improve: get `SDL Error: Texture dimensions are limited to 32768x32768` in `git grep` command.

### ISSUE THREAD

**Issue by sakurawald** [lem-project/lem#1631]
To reproduce:
1. Grep the source of lem using `git grep -nHI mouse`.
2. Click the `frontends/server/frontend/editor.js:178`.
3. Get the error.

![image](https://github.com/user-attachments/assets/c0650334-ed7e-4813-bd8a-67c1763ff9ac)

![image](https://github.com/user-attachments/assets/752b2cad-0e47-47f0-b1a2-ba5b181fd458)

**Comment by vindarel** [comment]
good find. 

Is it not related to clicking on the big "frontends/…/assets/index-JI7…_.js", and then on another file?

Also happens when scrolling.

**Comment by sakurawald** [comment]
> good find.

Yeah, the first time i found this is while scrolling my screen.

**Comment by cxxxr** [comment]
Thank you for your report.
I've fixed this bug now.
https://github.com/lem-project/lem/pull/1634

**Comment by vindarel** [comment]
Hello, on Discord a user reports that since that fix they content is split in half on screen.

The say this commit 71bebc2 is where it is introduced.

![](https://cdn.discordapp.com/attachments/1103927221204303892/1310482704516649031/Screenshot_2024-11-25_at_13.48.49.png?ex=6746b320&is=674561a0&hm=187494fe0564f0f1f4b76b0addce20808cf3a7b86a52b9dca1e3b5cb2f0e1ad4&)
