### ISSUE TITLE
Add ~/.roswell/local-projects to load-library search path

### ISSUE THREAD

**Issue by troydm** [lem-project/lem#538]
It wouldn't be harm to add ~/.roswell/local-projects to load-library path
As coded it's currently using (ql-symbol-value :*local-project-directories*) which is basically ql:*local-project-directories* variable, but unfortunately ~/.roswell/local-projects is not part of that variable list despite it being added to ASDF search registry

This happened when I tried to install https://github.com/koji-kojiro/lem-pygments-colorthemes using instructions specified in readme and had hard time figuring out why load-library was not working and color theme was not loading and there wasn't even a error message about what was happening, after moving koji-kojiro/lem-pygments-colorthemes from ~/.roswell/local-projects into ~/.roswell/lisp/quicklisp/local-projects everything works fine

**Comment by snmsts** [comment]
I disagree with the idea it wouldn't harm.
I intentionally remove paths which include one's home directory as absolute path on building lem.
It is because built binary might be used by different user from build user or distributed to different hardware which doesn't have the user.
I have hesitance to add "~/.roswell/" as load-path again as lem's official default load path.
I feel it should be user's decision and ``~/.lem/init.lisp`` would be the right place to do so.

**Comment by troydm** [comment]
@snmsts then maybe this should be documented in default .lemrc sample config as example, something like

(pushnew #P"~/.roswell/local-projects" ql:*local-projects-directories*)

**Comment by snmsts** [comment]
sounds reasonable..
that means add line on https://github.com/lem-project/lem/blob/master/lemrc-example...
My concern is would it be seen or not...

Is it ok to add @cxxxr ?

**Comment by cxxxr** [comment]
It's ok.
