### ISSUE TITLE
multiple cursor

### ISSUE THREAD

**Issue by cxxxr** [lem-project/lem#575]

**Comment by Gavinok** [comment]
I see that right now the current implementation requires the modification of a `define-command` for each function. Wouldn't it make more sense to have the advice (since in theory it should be the same for all uses of execute) global then allow for white and blacklisting of certain usecases.

For example remove the current advice and instead have this method be called as advice for every function.
```lisp
(defmethod lem:execute :around (mode command argument)
  (let ((currsor-support (getf lem-user::*multiple-cursor-whitelist* command)))
    (cond
     ((eq currsor-support :allow) (lem::process-each-cursors #'call-next-method))
     ((eq currsor-support :disallow) (call-next-method))
     (t (setf (getf lem-user::*multiple-cursor-whitelist* command)
                 (if (y-or-n-p "allow for multiple users") :allow :disallow)))))
```
I realize y-or-n-p isn't the greatest choice but I figure there is probably some prompting system I am unaware of that you expose.

**Comment by cxxxr** [comment]
Thank you.
This might be a good idea and I'll refer to it.

**Comment by cxxxr** [comment]
https://github.com/lem-project/lem/wiki/Multiple-cursors
