### ISSUE TITLE
About moving from gitter to discord

### ISSUE THREAD

**Issue by cxxxr** [lem-project/lem#614]
The main reason is that discord is more major and can be used for other purposes as well.
How about this?

**Comment by cxxxr** [comment]
I made it for a try.
https://discord.gg/HtN75wK5

**Comment by Sasanidas** [comment]
Maybe a more open source friendy solution it's possible?

Some time ago I read this interesting article (https://sneak.berlin/20200220/discord-is-not-an-acceptable-choice-for-free-software-projects/), it shows some alternatives but maybe [matrix](https://matrix.org/) can be appropriate?

Let me know what you think,

Regards

**Comment by cxxxr** [comment]
Thank you for sharing this interesting post.

I chose discord because there is already a large discord server for the lisp community, and I thought it would be easy to many people.

**Comment by Sasanidas** [comment]
I see, I mean is a totally legit reason, but I think it's also important to support maybe others form of communication, maybe a tool like https://github.com/42wim/matterbridge can be used to bridge both the discord channel AND the gitter one.

**Comment by cxxxr** [comment]
Oh, that sounds good.
Please give me some time to look into it.

**Comment by cxxxr** [comment]
@Sasanidas 
I am trying matterbridge but it is too much work and not working.
Also, you probably won't be able to see the discord's past logs.
Is it difficult to join the discord?

**Comment by Sasanidas** [comment]
Well... it's not difficult, I'll do it but I would also like investigate is there any possibility in the future other than discord.

**Comment by Sasanidas** [comment]
Seems like the discord link doesn't work :sweat_smile:

**Comment by seanfarley** [comment]
> Or maybe https://github.com/matrix-org/matrix-appservice-discord , given that gitter is basically matrix

I use matrix but don't recommend this appservice bridge because it makes every message have a `bot` label. I personally use [mautrix-discord](https://github.com/mautrix/discord) and it is pretty nice. It maps each discord server to a matrix space and handles subspaces as well, too.

> I am trying matterbridge but it is too much work and not working.

I found the same when I tried a few years ago :-)

> Also, you probably won't be able to see the discord's past logs.

I think this is true for every bridge (even the matrix ones).

> Is it difficult to join the discord?

I used to be very vocally against discord 😬 but the sad fact is that discord is very popular 😕 so it's kind of the default that people just use it. One of the most popular and healthy emacs communities, Doom Emacs, is on discord. Along with Emacs LSP, so I would say "it's fine" and not to worry about setting up bridges for now. You can always change your mind later 😄

**Comment by cxxxr** [comment]
> Seems like the invite discord link doesn't work 😅

How about the following link?
https://discord.gg/NHzqbw4zVR

**Comment by jcs090218** [comment]
I think it might be good to put up a discord link (badge) somewhere in the documentation.

**Comment by seanfarley** [comment]
> Well... it's not difficult, I'll do it but I would also like investigate is there any possibility in the future other than discord.

I really, really, really wish Matrix were better. I've used matrix for years now and I still don't recommend it. The notifications are always flaky. Rooms (channels) are just plain janky. It has *so* many sharp edges. If `lem` only wants one room / channel, then matrix is probably fine. I wish discord, slack, mattermost, and any other "solution" would just go away and we could all go back to IRC 😢

**Comment by Sasanidas** [comment]
> I wish discord, slack, mattermost, and any other "solution" would just go away and we could all go back to IRC cry

Agree 100%, IRC for life :+1:
