### ISSUE TITLE
How to get implement (region-active-p) and  (buffer-substring-no-properties) from Emacs Lisp in Lem with vi-mode?

### ISSUE THREAD

**Issue by Dima-369** [lem-project/lem#872]
I am using `(vi-mode)`.  One thing I just can't figure out from grepping over the sources, is how one would implement `(region-active-p)` from Emacs in Lem.

I want to create this function. With `(visual-p)`, I can detect if the vi visual modes are active, but not if at least one character is marked.

```lisp
(define-command dima-kill-line-or-region () ()
  (cond
   ((visual-p)
    (lem-vi-mode/visual:apply-visual-range
     (lambda (start end)
       ;; TODO: this crashes, how to implement this properly and only if at least 1 char is selected?
       (kill-region start (1+ end)))))
   (t
    (move-to-beginning-of-logical-line)
    (kill-line)
    (delete-next-char)
    (indent-line (current-point)))))
```

Basically, I would like to have this from Emacs Lisp in Lem:

```lisp
(when (region-active-p)
  (buffer-substring-no-properties (region-beginning) (region-end)))
```

Maybe it's trivial, but I just can't figure it out :)

**Comment by cxxxr** [comment]
It would be good to use `(buffer-mark-p (current-buffer))`.

**Comment by Dima-369** [comment]
> It would be good to use (buffer-mark-p (current-buffer)).

I tried it, it doesn't work. It always returns `nil` with `vi-mode`.

I tested it like this:

```lisp
(define-command dima-kill-line-or-region () ()
  (display-popup-message (format nil "~a ~a" (visual-p) (buffer-mark-p (current-buffer)))))
```

**Comment by Dima-369** [comment]
I suppose @theangelperalta would know how to do this since he did many `vi-mode` MRs. I suppose `(buffer-mark-p (current-buffer))` does not work since the visual vi-mode uses an overlay to designate the marked region.

**Comment by Sasanidas** [comment]
I think the main problem is that vi-mode is not using the region, it's implementing it's own visual overlay, so not using the Lem mark. So any command that expected a region doesn't work property, so I guess the idea would be to change the overlay functions on the visual.lisp to use the native mark of Lem rather than implement an overlay that only work with vi-mode commands.

**Comment by Sasanidas** [comment]
As a temporal solution, instead of using the region that way, you can use the vi-delete function, that will take into account the "region" of the vi-mode overlay (instead of using kill-region),

You can check how is done (as an example) here https://github.com/lem-project/lem/blob/4fe17c8711f95ec04a1f8de844e90c8d809a59ff/modes/vi-mode/commands.lisp#L344

As you can see, it's just calling vi-delete, having all the logic of detecting the overlay inside the function (well command in this case) inside.

**Comment by Dima-369** [comment]
> As you can see, it's just calling vi-delete, having all the logic of detecting the overlay inside the vi-delete function (well command in this case).

Aha, thanks for pointing me to `(vi-delete)`. So to answer my question:

```lisp
;; Emacs Lisp
(when (region-active-p)
  (buffer-substring-no-properties
   (region-beginning) (region-end)))

;; translates to this for vi-mode in Lem
;; see modes/vi-mode/commands.lisp

(when (visual-p)
  (with-output-to-string (out)
    (let ((*cursor-offset* 0))
      (apply-visual-range
       (lambda (start end)
         (unless (point< start end)
           (rotatef start end))
         (when (visual-line-p)
           (character-offset end 1))
         (write-string (points-to-string start end) out))))))

;; without vi-mode in Lem

(when (lem:buffer-mark-p (lem:current-buffer))
  (lem:points-to-string
   (lem:cursor-region-end (lem:current-point))
   (lem:cursor-region-beginning (lem:current-point))))
```

I suppose we can close this issue then?

**Comment by Sasanidas** [comment]
I think you can skip the current point on the cursor-region-end doing something like:
```
 (lem:with-point ((start (lem:region-beginning))
                   (end (lem:region-end)))
    (lem:points-to-string start end)))
```

In any case, I'll close this issue as it seems that you found the answer :)
